version: '3.6'

services:
  ci-build:
    image: mcr.microsoft.com/dotnet/core/sdk:3.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./BuildingModernWebApplications.sln && dotnet publish ./BuildingModernWebApplications.sln -c Release -o ./obj/Docker/publish"
